# Data Cleaning

This notebook loads the raw historical NFL player-season dataset, validates the data, calculates full-PPR fantasy points, and prepares a clean dataset for exploratory analysis and feature engineering.

In [1]:
import polars as pl

In [2]:
df  = pl.read_csv("../data/raw/player_stats_2016_2025.csv")

df.head()

shape: (5, 31)
┌────────────┬────────────┬──────────┬────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ player_id  ┆ player_dis ┆ position ┆ season ┆ … ┆ wopr     ┆ fantasy_po ┆ fantasy_po ┆ calculate │
│ ---        ┆ play_name  ┆ ---      ┆ ---    ┆   ┆ ---      ┆ ints       ┆ ints_ppr   ┆ d_fantasy │
│ str        ┆ ---        ┆ str      ┆ i64    ┆   ┆ f64      ┆ ---        ┆ ---        ┆ _points_p │
│            ┆ str        ┆          ┆        ┆   ┆          ┆ f64        ┆ f64        ┆ pr        │
│            ┆            ┆          ┆        ┆   ┆          ┆            ┆            ┆ ---       │
│            ┆            ┆          ┆        ┆   ┆          ┆            ┆            ┆ f64       │
╞════════════╪════════════╪══════════╪════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 00-0019596 ┆ Tom Brady  ┆ QB       ┆ 2016   ┆ … ┆ 0.0      ┆ 258.56     ┆ 258.56     ┆ 258.56    │
│ 00-0020337 ┆ Steve      ┆ WR       ┆ 2016   ┆ … ┆ 0.349021 ┆ 113.9      ┆ 183.9      ┆ 183.9     │
│            ┆ Smith      ┆          ┆        ┆   ┆          ┆            ┆            ┆           │
│ 00-0020531 ┆ Drew Brees ┆ QB       ┆ 2016   ┆ … ┆ 0.0      ┆ 332.32     ┆ 332.32     ┆ 332.32    │
│ 00-0020679 ┆ Shaun Hill ┆ QB       ┆ 2016   ┆ … ┆ 0.0      ┆ 10.18      ┆ 10.18      ┆ 10.18     │
│ 00-0021206 ┆ Josh       ┆ QB       ┆ 2016   ┆ … ┆ 0.0      ┆ 52.1       ┆ 52.1       ┆ 52.1      │
│            ┆ McCown     ┆          ┆        ┆   ┆          ┆            ┆            ┆           │
└────────────┴────────────┴──────────┴────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [3]:
print(df.shape)
df.group_by("season").len().sort("season")

(5874, 31)

shape: (10, 2)
┌────────┬─────┐
│ season ┆ len │
│ ---    ┆ --- │
│ i64    ┆ u32 │
╞════════╪═════╡
│ 2016   ┆ 557 │
│ 2017   ┆ 553 │
│ 2018   ┆ 577 │
│ 2019   ┆ 572 │
│ 2020   ┆ 602 │
│ 2021   ┆ 633 │
│ 2022   ┆ 608 │
│ 2023   ┆ 576 │
│ 2024   ┆ 588 │
│ 2025   ┆ 608 │
└────────┴─────┘

In [4]:
# Checking for low participation players

df.filter(
    pl.col("games") <= 2
).select([
    "player_display_name",
    "position",
    "season",
    "recent_team",
    "games",
    "fantasy_points_ppr"
]).sort(
    ["season", "position", "fantasy_points_ppr"],
    descending=[False, False, True]
)

shape: (827, 6)
┌─────────────────────┬──────────┬────────┬─────────────┬───────┬────────────────────┐
│ player_display_name ┆ position ┆ season ┆ recent_team ┆ games ┆ fantasy_points_ppr │
│ ---                 ┆ ---      ┆ ---    ┆ ---         ┆ ---   ┆ ---                │
│ str                 ┆ str      ┆ i64    ┆ str         ┆ i64   ┆ f64                │
╞═════════════════════╪══════════╪════════╪═════════════╪═══════╪════════════════════╡
│ Nick Foles          ┆ QB       ┆ 2016   ┆ KC          ┆ 2     ┆ 28.0               │
│ Charlie Whitehurst  ┆ QB       ┆ 2016   ┆ CLE         ┆ 1     ┆ 9.38               │
│ Mike Glennon        ┆ QB       ┆ 2016   ┆ TB          ┆ 1     ┆ 9.0                │
│ Scott Tolzien       ┆ QB       ┆ 2016   ┆ IND         ┆ 2     ┆ 8.94               │
│ Geno Smith          ┆ QB       ┆ 2016   ┆ NYJ         ┆ 2     ┆ 7.94               │
│ …                   ┆ …        ┆ …      ┆ …           ┆ …     ┆ …                  │
│ DJ Turner           ┆ WR       ┆ 2025   ┆ LV          ┆ 1     ┆ 0.0                │
│ Mecole Hardman      ┆ WR       ┆ 2025   ┆ BUF         ┆ 2     ┆ 0.0                │
│ Kaden Davis         ┆ WR       ┆ 2025   ┆ CLE         ┆ 1     ┆ 0.0                │
│ Dalevon Campbell    ┆ WR       ┆ 2025   ┆ CAR         ┆ 1     ┆ 0.0                │
│ Parris Campbell     ┆ WR       ┆ 2025   ┆ DAL         ┆ 1     ┆ 0.0                │
└─────────────────────┴──────────┴────────┴─────────────┴───────┴────────────────────┘

In [5]:
df.filter(
    pl.col("games") <= 2
).height

827

In [6]:
# Recalculating and locking in my PPR target

df = df.with_columns(
    (
        pl.col("passing_yards") / 25
        + pl.col("passing_tds") * 4
        - pl.col("passing_interceptions") * 2

        + pl.col("rushing_yards") / 10
        + pl.col("rushing_tds") * 6

        + pl.col("receiving_yards") / 10
        + pl.col("receptions")
        + pl.col("receiving_tds") * 6

        + pl.col("passing_2pt_conversions") * 2
        + pl.col("rushing_2pt_conversions") * 2
        + pl.col("receiving_2pt_conversions") * 2

        + pl.col("special_teams_tds") * 6

        - (
            pl.col("sack_fumbles_lost")
            + pl.col("rushing_fumbles_lost")
            + pl.col("receiving_fumbles_lost")
        ) * 2
    ).alias("fantasy_points_ppr_calc")
)

In [7]:
df = df.with_columns(
    (
        pl.col("fantasy_points_ppr_calc")
        - pl.col("fantasy_points_ppr")
    ).alias("fantasy_points_difference")
)

df.select(
    pl.col("fantasy_points_difference").abs().mean().alias("mean_abs_difference"),
    pl.col("fantasy_points_difference").abs().max().alias("max_abs_difference")
)

shape: (1, 2)
┌─────────────────────┬────────────────────┐
│ mean_abs_difference ┆ max_abs_difference │
│ ---                 ┆ ---                │
│ f64                 ┆ f64                │
╞═════════════════════╪════════════════════╡
│ 1.0445e-15          ┆ 5.6843e-14         │
└─────────────────────┴────────────────────┘

In [8]:
# Saving cleaned dataset

clean_path  = "../data/processed/player_stats_clean_2016_2025"

df.write_csv(clean_path)

In [9]:
import os

os.path.exists(clean_path)

True